@PraktykiAPI_HostAddress = https://localhost:7164

@emplID=0
POST {{PraktykiAPI_HostAddress}}/api/workdays/emplPanel/workday/start/1

###

PUT {{PraktykiAPI_HostAddress}}/api/workdays/emplPanel/workday/end/{{emplID}}

###

GET {{PraktykiAPI_HostAddress}}/api/workdays/emplPanel/workday/status/{{emplID}}

###

@id=0
GET {{PraktykiAPI_HostAddress}}/api/employees/employee/{{id}}

###

GET {{PraktykiAPI_HostAddress}}/api/day_off/daysoff

###

GET {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/status/{{emplID}}

###

POST {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/start/{{emplID}}

###

PUT {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/end/{{emplID}}

###

GET {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/status/1

###

GET {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/status/1

###

GET {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/status/{{emplID}}

###

GET {{PraktykiAPI_HostAddress}}/api/workdays/emplPanel/workday/status/{{emplID}}

###

GET {{PraktykiAPI_HostAddress}}/api/breaks/emplPanel/workday/break/status/{{emplID}}

###
