// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PraktykiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319123214_PhoneNumberNoLongerRequired")]
    partial class PhoneNumberNoLongerRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PraktykiAPI.Models.Break", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("BreakEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BreakStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkDayID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkDayID");

                    b.ToTable("Breaks");
                });

            modelBuilder.Entity("PraktykiAPI.Models.DayOff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AcceptStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("DaysOff");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WorkEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStart")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("WorkSchedule");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AutoEndWorkdayLengthInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinBreakBetweenWorkdaysInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinBreakLengthInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinWorkdayLengthForBreakInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinWorkdayLengthInMinutes")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("WorkSettings");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Break", b =>
                {
                    b.HasOne("PraktykiAPI.Models.WorkDay", "WorkDay")
                        .WithMany("Breaks")
                        .HasForeignKey("WorkDayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("PraktykiAPI.Models.DayOff", b =>
                {
                    b.HasOne("PraktykiAPI.Models.Employee", "Employee")
                        .WithMany("DaysOff")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.HasOne("PraktykiAPI.Models.Employee", "Employee")
                        .WithMany("WorkDays")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Employee", b =>
                {
                    b.Navigation("DaysOff");

                    b.Navigation("WorkDays");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.Navigation("Breaks");
                });
#pragma warning restore 612, 618
        }
    }
}
