// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PraktykiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310122350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PraktykiAPI.Models.Break", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeOnly?>("Break_End_Hour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Break_Start_Hour")
                        .HasColumnType("time");

                    b.Property<int>("WorkDay_Id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkDay_Id");

                    b.ToTable("Break_Timetable");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Day_Off", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("End_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Days_Off");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PraktykiAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Is_Active")
                        .HasColumnType("int");

                    b.Property<int>("Is_LogIn")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Employee_ID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Work_End_Hour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Work_Start_Hour")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.HasIndex("Employee_Id");

                    b.ToTable("Work_Timetable");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Break", b =>
                {
                    b.HasOne("PraktykiAPI.Models.WorkDay", "WorkDay")
                        .WithMany("Breaks")
                        .HasForeignKey("WorkDay_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Day_Off", b =>
                {
                    b.HasOne("PraktykiAPI.Models.Employee", "Employee")
                        .WithMany("Days_Off")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PraktykiAPI.Models.User", b =>
                {
                    b.HasOne("PraktykiAPI.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("PraktykiAPI.Models.User", "Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.HasOne("PraktykiAPI.Models.Employee", "Employee")
                        .WithMany("WorkDays")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PraktykiAPI.Models.Employee", b =>
                {
                    b.Navigation("Days_Off");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("WorkDays");
                });

            modelBuilder.Entity("PraktykiAPI.Models.WorkDay", b =>
                {
                    b.Navigation("Breaks");
                });
#pragma warning restore 612, 618
        }
    }
}
